"""HTTP-facing facade for Model Center application operations."""

from app.features.model_config.management import (
    ManagementOperationError,
    bindings_page,
    catalog_page,
    connections_page,
    create_connection,
    create_certification,
    create_prompt_profile_draft,
    create_prompt_profile_versioned,
    create_recipe,
    drivers_page,
    get_certification,
    impact_preview,
    overview,
    publish_prompt_profile_version,
    prompt_profiles_page,
    publish_recipe,
    recipes_page,
    recipe_bindings_display,
    rollback_prompt_profile,
    rollback_recipe,
    test_connection,
    update_connection,
    unavailable,
    validate_recipe_version,
)
from app.features.model_config.prompt_assistance import (
    get_prompt_profile_detail,
    optimize_prompt_profile,
    preview_prompt_profile,
)


__all__ = [
    "ManagementOperationError",
    "bindings_page",
    "catalog_page",
    "connections_page",
    "create_connection",
    "create_certification",
    "create_prompt_profile_draft",
    "create_prompt_profile_versioned",
    "create_recipe",
    "drivers_page",
    "get_certification",
    "get_prompt_profile_detail",
    "optimize_prompt_profile",
    "impact_preview",
    "overview",
    "publish_prompt_profile_version",
    "prompt_profiles_page",
    "preview_prompt_profile",
    "publish_recipe",
    "recipes_page",
    "recipe_bindings_display",
    "rollback_prompt_profile",
    "rollback_recipe",
    "test_connection",
    "update_connection",
    "unavailable",
    "validate_recipe_version",
]
