"""Volcano Ark Agent Plan provider and model catalog.

Agent Plan uses a dedicated API key and a dedicated /api/plan/v3 base URL.
Keep it separate from the regular Volcano provider so users can configure both
without mixing quotas, endpoints, or model names.
"""

VOLCANO_AGENT_PLAN_PROVIDER_ID = "volcano_agent_plan"
VOLCANO_AGENT_PLAN_BASE_URL = "https://ark.cn-beijing.volces.com/api/plan/v3"

VOLCANO_AGENT_PLAN_PROVIDER = {
    "id": VOLCANO_AGENT_PLAN_PROVIDER_ID,
    "name": VOLCANO_AGENT_PLAN_PROVIDER_ID,
    "name_cn": "火山方舟 Agent Plan",
    "name_en": "Volcano Ark Agent Plan",
    "provider_type": "cloud",
    "base_url": VOLCANO_AGENT_PLAN_BASE_URL,
    "auth_type": "bearer",
    "is_active": True,
    "is_builtin": True,
    "description": "火山方舟 Agent Plan 订阅套餐，使用专属 API Key 与 /api/plan/v3 端点，覆盖文本、向量、图像和视频模型。",
    "website_url": "https://console.volcengine.com/ark",
    "doc_url": "https://www.volcengine.com/docs/82379",
    "icon_url": "/icons/volcano.svg",
}


def _agent_model(
    *,
    suffix: str,
    model_id: str,
    model_name_cn: str,
    model_type: str,
    capabilities: list[str],
    context_window: int = 0,
    max_tokens: int = 0,
    input_cost_per_1k: float = 0.0,
    output_cost_per_1k: float = 0.0,
    supports_streaming: bool = True,
    supports_function_calling: bool = False,
    supports_vision: bool = False,
    supports_json_mode: bool = False,
    is_recommended: bool = False,
    description: str = "",
) -> dict:
    return {
        "id": f"vplan-{suffix}",
        "provider_id": VOLCANO_AGENT_PLAN_PROVIDER_ID,
        "model_id": model_id,
        "model_name": model_id,
        "model_name_cn": model_name_cn,
        "model_type": model_type,
        "capabilities": capabilities,
        "context_window": context_window,
        "max_tokens": max_tokens,
        "input_cost_per_1k": input_cost_per_1k,
        "output_cost_per_1k": output_cost_per_1k,
        "supports_streaming": supports_streaming,
        "supports_function_calling": supports_function_calling,
        "supports_vision": supports_vision,
        "supports_json_mode": supports_json_mode,
        "is_active": True,
        "is_recommended": is_recommended,
        "description": description,
        "base_url": VOLCANO_AGENT_PLAN_BASE_URL,
    }


VOLCANO_AGENT_PLAN_MODELS = [
    _agent_model(
        suffix="ark-code-latest",
        model_id="ark-code-latest",
        model_name_cn="Ark Code Latest",
        model_type="chat",
        capabilities=["chat", "completion", "vision", "code_generation", "agent_plan"],
        context_window=256000,
        max_tokens=4096,
        input_cost_per_1k=2.5,
        output_cost_per_1k=2.5,
        supports_function_calling=True,
        supports_vision=True,
        supports_json_mode=True,
        is_recommended=True,
        description="Agent Plan 推荐编码/Agent 文本模型，OpenAI 兼容调用，支持图文输入。",
    ),
    _agent_model(
        suffix="doubao-seed-2-0-code",
        model_id="doubao-seed-2.0-code",
        model_name_cn="豆包 Seed 2.0 Code",
        model_type="chat",
        capabilities=["chat", "completion", "vision", "code_generation", "agent_plan"],
        context_window=256000,
        max_tokens=4096,
        input_cost_per_1k=2.5,
        output_cost_per_1k=2.5,
        supports_function_calling=True,
        supports_vision=True,
        supports_json_mode=True,
        is_recommended=True,
        description="Agent Plan 进阶文本/编码模型，适合剧本结构化、提示词规划和复杂生成编排。",
    ),
    _agent_model(
        suffix="doubao-seed-2-0-pro",
        model_id="doubao-seed-2.0-pro",
        model_name_cn="豆包 Seed 2.0 Pro",
        model_type="chat",
        capabilities=["chat", "completion", "vision", "agent_plan"],
        context_window=256000,
        max_tokens=4096,
        input_cost_per_1k=2.5,
        output_cost_per_1k=2.5,
        supports_function_calling=True,
        supports_vision=True,
        supports_json_mode=True,
        is_recommended=True,
        description="Agent Plan 进阶文本模型，适合长章节生成、角色设定和分镜连续性推理。",
    ),
    _agent_model(
        suffix="doubao-seed-2-0-lite",
        model_id="doubao-seed-2.0-lite",
        model_name_cn="豆包 Seed 2.0 Lite",
        model_type="chat",
        capabilities=["chat", "completion", "vision", "agent_plan"],
        context_window=256000,
        max_tokens=4096,
        input_cost_per_1k=0.5,
        output_cost_per_1k=0.5,
        supports_vision=True,
        supports_json_mode=True,
        is_recommended=True,
        description="Agent Plan 标准文本模型，适合常规小说、剧本和分镜生成。",
    ),
    _agent_model(
        suffix="doubao-seed-2-0-mini",
        model_id="doubao-seed-2.0-mini",
        model_name_cn="豆包 Seed 2.0 Mini",
        model_type="chat",
        capabilities=["chat", "completion", "vision", "agent_plan"],
        context_window=256000,
        max_tokens=4096,
        input_cost_per_1k=0.25,
        output_cost_per_1k=0.25,
        supports_vision=True,
        is_recommended=False,
        description="Agent Plan 极速文本模型，适合轻量提示词、摘要和低成本批处理。",
    ),
    _agent_model(
        suffix="deepseek-v3-2",
        model_id="deepseek-v3.2",
        model_name_cn="DeepSeek V3.2",
        model_type="chat",
        capabilities=["chat", "completion", "reasoning", "agent_plan"],
        context_window=128000,
        max_tokens=4096,
        input_cost_per_1k=2.5,
        output_cost_per_1k=2.5,
        supports_json_mode=True,
        description="Agent Plan 进阶文本模型，适合长文分析和逻辑规划。",
    ),
    _agent_model(
        suffix="deepseek-v4-flash-beta",
        model_id="deepseek-v4-flash-beta",
        model_name_cn="DeepSeek V4 Flash Beta",
        model_type="chat",
        capabilities=["chat", "completion", "long_context", "agent_plan"],
        context_window=1000000,
        max_tokens=384000,
        input_cost_per_1k=0.5,
        output_cost_per_1k=0.5,
        description="Agent Plan 标准长上下文模型，适合长篇资料分析。",
    ),
    _agent_model(
        suffix="deepseek-v4-pro-beta",
        model_id="deepseek-v4-pro-beta",
        model_name_cn="DeepSeek V4 Pro Beta",
        model_type="chat",
        capabilities=["chat", "completion", "long_context", "reasoning", "agent_plan"],
        context_window=1000000,
        max_tokens=384000,
        input_cost_per_1k=4.5,
        output_cost_per_1k=5.5,
        description="Agent Plan 高阶长上下文模型，适合复杂推理和大纲重构。",
    ),
    _agent_model(
        suffix="glm-5-1",
        model_id="glm-5.1",
        model_name_cn="GLM 5.1",
        model_type="chat",
        capabilities=["chat", "completion", "vision", "agent_plan"],
        context_window=200000,
        max_tokens=4096,
        input_cost_per_1k=4.5,
        output_cost_per_1k=4.5,
        supports_vision=True,
        description="Agent Plan 进阶文本模型，支持图文输入。",
    ),
    _agent_model(
        suffix="kimi-k2-6",
        model_id="kimi-k2.6",
        model_name_cn="Kimi K2.6",
        model_type="chat",
        capabilities=["chat", "completion", "long_context", "agent_plan"],
        context_window=256000,
        max_tokens=4096,
        input_cost_per_1k=4.5,
        output_cost_per_1k=4.5,
        description="Agent Plan 进阶文本模型，适合长文本创作和审阅。",
    ),
    _agent_model(
        suffix="minimax-m2-7",
        model_id="minimax-m2.7",
        model_name_cn="MiniMax M2.7",
        model_type="chat",
        capabilities=["chat", "completion", "long_context", "agent_plan"],
        context_window=1000000,
        max_tokens=4096,
        input_cost_per_1k=2.5,
        output_cost_per_1k=2.5,
        description="Agent Plan 进阶超长上下文文本模型。",
    ),
    _agent_model(
        suffix="doubao-embedding-vision",
        model_id="doubao-embedding-vision",
        model_name_cn="豆包 Embedding Vision",
        model_type="embedding",
        capabilities=["embedding", "vision", "multimodal_embedding", "agent_plan"],
        context_window=256000,
        input_cost_per_1k=0.5,
        output_cost_per_1k=0.5,
        supports_streaming=False,
        supports_vision=True,
        description="Agent Plan 向量化模型，适合后续扩展素材检索和图文语义检索。",
    ),
    _agent_model(
        suffix="seedream-5-0-lite",
        model_id="doubao-seedream-5.0-lite",
        model_name_cn="豆包 Seedream 5.0 Lite",
        model_type="image-generation",
        capabilities=["text-to-image", "image-to-image", "character_reference", "scene_reference", "agent_plan"],
        max_tokens=0,
        supports_streaming=False,
        is_recommended=True,
        description="Agent Plan 图像生成模型，适合小说封面、角色立绘、场景和道具参考图。",
    ),
    _agent_model(
        suffix="seedance-1-5-pro",
        model_id="doubao-seedance-1.5-pro",
        model_name_cn="豆包 Seedance 1.5 Pro",
        model_type="video-generation",
        capabilities=["text-to-video", "image-to-video", "agent_plan"],
        supports_streaming=False,
        description="Agent Plan 视频生成模型；Small 套餐不支持视频生成。",
    ),
    _agent_model(
        suffix="seedance-2-0",
        model_id="doubao-seedance-2.0",
        model_name_cn="豆包 Seedance 2.0",
        model_type="video-generation",
        capabilities=["text-to-video", "image-to-video", "audio-video-generation", "agent_plan"],
        supports_streaming=False,
        is_recommended=True,
        description="Agent Plan Seedance 2.0 视频生成模型，支持有声/无声视频任务。",
    ),
    _agent_model(
        suffix="seedance-2-0-fast",
        model_id="doubao-seedance-2.0-fast",
        model_name_cn="豆包 Seedance 2.0 Fast",
        model_type="video-generation",
        capabilities=["text-to-video", "image-to-video", "audio-video-generation", "agent_plan"],
        supports_streaming=False,
        is_recommended=True,
        description="Agent Plan Seedance 2.0 Fast 视频生成模型，适合批量镜头草稿和快速预览。",
    ),
]


def find_volcano_agent_plan_model(model_id: str) -> dict | None:
    """Resolve an Agent Plan catalog model by its product-facing identifier."""
    return next((model for model in VOLCANO_AGENT_PLAN_MODELS if model["id"] == model_id), None)
