"""Product-facing Volcano image model catalog seeds."""

SEEDREAM_50_PRO_API_MODEL_ID = "doubao-seedream-5-0-260128"
SEEDREAM_50_PRO_CATALOG_ID = "doubao-seedream-5.0-pro"


VOLCANO_IMAGE_MODEL_SEEDS = [
    {
        "id": "doubao-seedream-4.5",
        "provider_id": "volcano",
        "model_id": "Doubao-Seedream-4.5",
        "model_name": "Doubao-Seedream-4.5",
        "model_name_cn": "豆包Seedream-4.5",
        "model_type": "image-generation",
        "capabilities": ["text-to-image", "image-edit", "inpainting", "outpainting"],
        "context_window": 4096,
        "max_tokens": 4096,
        "input_cost_per_1k": 0.05,
        "output_cost_per_1k": 0.05,
        "supports_streaming": False,
        "supports_function_calling": False,
        "supports_vision": False,
        "supports_json_mode": False,
        "is_active": True,
        "is_recommended": True,
        "description": "火山引擎高质量图像生成模型，支持文生图、图像编辑等",
        "version": "4.5",
        "release_date": "2026-03-01",
        "endpoint_id": "ep-20260320112226-rgndq",
    },
    {
        "id": "doubao-seedream-5.0-lite",
        "provider_id": "volcano",
        "model_id": "Doubao-Seedream-5.0-lite",
        "model_name": "Doubao-Seedream-5.0-lite",
        "model_name_cn": "豆包Seedream-5.0-lite",
        "model_type": "image-generation",
        "capabilities": ["text-to-image", "image-edit", "inpainting"],
        "context_window": 4096,
        "max_tokens": 4096,
        "input_cost_per_1k": 0.02,
        "output_cost_per_1k": 0.02,
        "supports_streaming": False,
        "supports_function_calling": False,
        "supports_vision": False,
        "supports_json_mode": False,
        "is_active": True,
        "is_recommended": True,
        "description": "豆包轻量级图像生成模型，性价比高",
        "version": "5.0-lite",
        "release_date": "2026-03-01",
        "endpoint_id": "ep-20260320113731-jzjkn",
    },
    {
        "id": SEEDREAM_50_PRO_CATALOG_ID,
        "provider_id": "volcano",
        "model_id": SEEDREAM_50_PRO_API_MODEL_ID,
        "model_name": "Seedream 5.0 Pro",
        "model_name_cn": "豆包 Seedream 5.0 Pro",
        "model_type": "image-generation",
        "capabilities": [
            "text-to-image",
            "image-edit",
            "multi-reference",
            "sequential-image-generation",
        ],
        "context_window": 0,
        "max_tokens": 0,
        "input_cost_per_1k": 0,
        "output_cost_per_1k": 0,
        "supports_streaming": True,
        "supports_function_calling": False,
        "supports_vision": False,
        "supports_json_mode": False,
        "is_active": True,
        "is_recommended": True,
        "description": "火山方舟 Seedream 5.0 非 Lite 旗舰生图模型，支持文生图、图像编辑、多参考图与组图生成",
        "version": "5.0-pro",
        "release_date": "2026-01-28",
        "endpoint_id": SEEDREAM_50_PRO_API_MODEL_ID,
    },
]
